services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - redis
    networks:
      - cqrs-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cqrs-network

  worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    command: php artisan queue:work redis --queue=commands,projections --tries=3 --verbose
    depends_on:
      - app
      - redis
    restart: unless-stopped
    networks:
      - cqrs-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - cqrs-network

  frontend:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - nginx
    networks:
      - cqrs-network

volumes:
  redis-data:

networks:
  cqrs-network:
    driver: bridge
